version: '3'

includes:
  docker:
    taskfile: docker/Taskfile.yaml
    dir: docker

tasks:
  default:
      desc: "List all services"
      cmds:
        - task --list

  deploy:
    desc: "Build Docker image and deploy via Helm"
    cmds:
      - docker build -t llm-fast-wrapper:local .
      - helm upgrade --install llm deploy/charts/llm-fast-wrapper --namespace llm --create-namespace --set llm.backend=openai --set llm.openai.apiKey=$OPENAI_API_KEY
