apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-fast-wrapper
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/llm-fast-wrapper
    targetRevision: main
    path: charts/llm-fast-wrapper
  destination:
    server: https://kubernetes.default.svc
    namespace: llm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
