services:
  postgres:
    extends:
      file: tools/pgvector/pgvector.yaml
      service: postgres
    profiles: ["pgvector"]

  pgadmin:
    extends:
      file: tools/pgvector/pgvector.yaml
      service: pgadmin
    profiles: ["pgvector"]

  splunk:
    extends:
      file: tools/splunk/splunk.yaml
      service: splunk
    profiles: ["splunk"]

  prometheus:
    extends:
      file: tools/prometheus/prometheus.yaml
      service: prometheus
    profiles: ["prometheus"]

volumes:
  pgdata:
  pgadmin-data:
  splunk-data:

networks:
  observability:
    driver: bridge