version: "3.9"

services:
  postgres:
    extends:
      file: tools/pgvector.yaml
      service: postgres

  pgadmin:
    extends:
      file: tools/pgvector.yaml
      service: pgadmin

  splunk:
    extends:
      file: tools/splunk.yaml
      service: splunk

  prometheus:
    extends:
      file: tools/prometheus.yaml
      service: prometheus

volumes:
  pgdata:
  pgadmin-data:
  splunk-data:

networks:
  observability:
    driver: bridge