version: '3.0'

env:
  DOCKER_ENV_FILE: ./local.env
  DOCKER_COMPOSE_FILE: docker-compose.yaml
  COMMON_FLAGS: --env-file {{.DOCKER_ENV_FILE}} -f {{.DOCKER_COMPOSE_FILE}}

tasks:
  up:
    desc: "Start all services"
    cmds:
      - docker compose {{.COMMON_FLAGS}} --profile splunk --profile pgvector --profile pgadmin --profile prometheus up -d --build

  down:
    desc: "Stop all services and remove containers"
    cmds:
      - docker compose {{.COMMON_FLAGS}} --profile splunk --profile pgvector --profile pgadmin --profile prometheus down --volumes --remove-orphans
      - docker ps -aq -f status=exited | xargs -r docker rm || echo "No exited containers to remove."

  db:up:
    desc: "Start all services"
    cmds:
      - docker compose {{.COMMON_FLAGS}}  --profile pgvector --profile pgadmin  up -d --build

  db:down:
    desc: "Stop all services and remove containers"
    cmds:
      - docker compose {{.COMMON_FLAGS}}  --profile pgvector --profile pgadmin  down --volumes --remove-orphans
      - docker ps -aq -f status=exited | xargs -r docker rm || echo "No exited containers to remove."

  restart:
    desc: "Rebuild and restart all services"
    cmds:
      - task: down
      - task: up

  ps:
    desc: "List running containers"
    cmds:
      - docker compose {{.COMMON_FLAGS}} --profile splunk --profile pgvector --profile pgadmin --profile prometheus ps --all

  logs:
    desc: "Tail logs for all services"
    cmds:
      - docker compose {{.COMMON_FLAGS}} --profile splunk --profile pgvector --profile pgadmin --profile prometheus logs -f

  open-splunk:
    desc: "Open Splunk UI in browser"
    cmds:
      - open http://localhost:8000

  open-prometheus:
    desc: "Open Prometheus UI in browser"
    cmds:
      - open http://localhost:9090

  open-pgadmin:
    desc: "Open pgAdmin UI in browser"
    cmds:
      - open http://localhost:5050

  check-health:
    desc: "Show container health status"
    cmds:
      - |
        docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep -E 'postgres|pgadmin|splunk|prometheus' || echo "No containers found"

