name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test ./...
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go build -o llm-fast-wrapper ./cmd/main.go
      - uses: softprops/action-gh-release@v2
        with:
          files: llm-fast-wrapper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
